apiVersion: apps/v1
kind: Deployment
metadata:
  name: stf-nginx
  namespace: stf-devicefarm
  labels:
    app: stf-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stf-nginx
  template:
    metadata:
      labels:
        app: stf-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: nginx-config
        configMap:
          name: stf-config
---
apiVersion: v1
kind: Service
metadata:
  name: stf-nginx
  namespace: stf-devicefarm
  labels:
    app: stf-nginx
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    name: http
    nodePort: 30080
  - port: 443
    targetPort: 443
    name: https
    nodePort: 30443
  selector:
    app: stf-nginx
