apiVersion: v1
kind: PersistentVolume
metadata:
  name: stf-rethinkdb-pv
  namespace: stf-devicefarm
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/ws0455/Desktop/device_farm/storage/rethinkdb
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stf-rethinkdb-pvc
  namespace: stf-devicefarm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
