apiVersion: apps/v1
kind: Deployment
metadata:
  name: stf-rethinkdb
  namespace: stf-devicefarm
  labels:
    app: stf-rethinkdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stf-rethinkdb
  template:
    metadata:
      labels:
        app: stf-rethinkdb
    spec:
      containers:
      - name: rethinkdb
        image: rethinkdb:2.4.2
        ports:
        - containerPort: 28015
          name: driver
        - containerPort: 8080
          name: admin
        command: ["rethinkdb", "--bind", "all", "--cache-size", "2048"]
        volumeMounts:
        - name: rethinkdb-data
          mountPath: /data
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: rethinkdb-data
        persistentVolumeClaim:
          claimName: stf-rethinkdb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: stf-rethinkdb
  namespace: stf-devicefarm
  labels:
    app: stf-rethinkdb
spec:
  ports:
  - port: 28015
    targetPort: 28015
    name: driver
  - port: 8080
    targetPort: 8080
    name: admin
  selector:
    app: stf-rethinkdb
